---
- name: Deploy Simple Web Service with Docker
  hosts: localhost
  become: yes
  
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Run Nginx container
      docker_container:
        name: ansible-app
        image: nginx:alpine
        state: started
        ports:
          - "8081:80"